Binary ops for interpretor (need to add logical or, and , bitwise operators except shifts)
AlexShmak/fp2023 pull request #14
Opened 2024-01-09 21:05 UTC by AlexShmak

2024-01-10 00:50 UTC, Kuarni requested changes
cringe

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +(* TODO: add support for BigInts ( like 2n ) *)
BigInt не будем поддерживать

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreterTests.ml
> +;;
дублируются тесты

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
cringe
сделай просто отрицание ответа
как вариант сделать унарный оператор логического отрицания и передать ответ в него

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
предварительно напишу, что if true then true - cringe
return (VBool (a = b))

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  then return (VBool false)
не понял смысл этого куска кода, null приводится к нулю и его нестрогое сравнение с нулем и так вернет false (если я ошибаюсь отпишись)

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    let b_checked = if b = VNull then VNumber 0. else b in
тот же самый момент с приведением, СМОТРИ ТОТ КОД, что уже написан

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
весь код - просто запуск less_than с переставленными аргументами, для этого даже отдельная функция не нужна

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    if is_to_string a_checked || is_to_string b_checked
все до этого можно было записать одной строкой
if is_to_string a && is_to_string b

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +      (VBool (greater_than a b = return (VBool true) || equal a b = return (VBool true)))
также, просто запуск less_eq

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
если не получится пофиксить коротко, то просто фигачь перебор всех операторов

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +let div a b = bop_with_num ( /. ) a b
не нужны отдельные функции

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
Бля, ну читай документацию, я зачем скидывал
ту свои приведения, все считается по разному.
Просто захуярь strict_equal с отдельным поведением, где распиши все кейсы отдельно (возможно где-то можно будет обобщить), а если он вернул false, то запускай с приведением типов (К ЧИСЛУ). И не заставляй меня больше самому лезть в документацию и разбираться, а то мне быстрее самому все это написать, чем отзывы строчить

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +;;
просто вызов strict_eq с отрицанием, тебя код не учили обобщать?

2024-01-10 00:50 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +      (VBool (less_than a b = return (VBool true) || equal a b = return (VBool true)))
`let x, y = if is_to_string a && is_to_string b then (приведение типов) in
 both (fun f -> f x y) less equal >>= fun (l, eq) -> l || eq (на счет работоспособность мной написанной конструкции не уверен, но выглядит круто) `

2024-01-10 19:26 UTC, AlexShmak commented on Javascript/lib/interpreter.ml
> +;;
нельзя просто взять strict_eq с отрицанием, ровно как и в not_eq. где от return ( *** ) взять отрицание

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +        | VNumber x when Float.is_nan x || x = 0. -> false
не понял зачем, но ладно

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +
оно ж просто копирует предыдущий, за исключением того, что у нас в Int 31/63 байта, а Int32 - 32

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +        | _ -> true))
я же писал, что if true then true кринж, просто распакуй значение op a b >>= get_vbool >>| fun x -> VBool (not x)

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +let strict_equal a b = return (VBool (a = b))
Неожиданно для меня оно работает так, как надо

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +    | VNumber a when Float.is_nan a -> true
вообще не пон зачем эта строчка, null == 0 в JS дает false

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  then bop_logical_with_string ( = ) a b
проблема с приоритетами, объекты должны приводится, только если strict дал false, так что надо скорее все что-нибудь такое `strict_equal a b >>= function | VBool false -> вот эти ifы | _ as x -> x`

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
>  let exp a b = bop_with_num ( ** ) a b
как уже писал, для таких мелких отдельная функция не нужна

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
>    then return (VBool true)
нет никакого смысла

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  then return (VBool false)
нет смысла

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  then return (VBool false)
нет смысла

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
>  ;;
видимо ты вообще нифига не понял, `if is_to_string then to_string else to_num >>= less || eq`

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  if x then if y then return b_preserved else return b_preserved else return a_preserved
`>>| function | (true, _) -> b_pres | _ -> a_pres `

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/interpreter.ml
> +  >>= fun (x, _) -> if x then return a_preserved else return b_preserved
аналогично верхнему

2024-01-12 17:35 UTC, Kuarni commented on Javascript/lib/parser.ml
> +  , Left (*precedence 10*) )
скобки вроде не нужны

2024-01-12 17:37 UTC, AlexShmak commented on Javascript/lib/interpreter.ml
> +        | VNumber x when Float.is_nan x || x = 0. -> false
потому что до этого оно работало неправильно

2024-01-12 17:47 UTC, AlexShmak commented on Javascript/lib/parser.ml
> +  , Left (*precedence 10*) )
скобки расставил ocamlformat

2024-01-12 21:08 UTC, AlexShmak commented on Javascript/lib/interpreter.ml
> +
нет, в bop_bitwise_shift нужно брать Int32.to_int от y в конце

2024-01-12 21:08 UTC, AlexShmak commented on Javascript/lib/interpreter.ml
> +
а get_int обобщил

2024-01-13 00:03 UTC, Kuarni approved these changes
сойдет, уже в финале буду чистить

2024-01-13 00:03 UTC, Kuarni commented on Javascript/lib/interpreter.ml
>  ;;
и эта фигня все еще работает неправильно, почему нельзя просто следовать моим указаниям

2024-01-13 00:03 UTC, merged